services:
  # Rust Lang Slim
  rust:
    build:
      context: ./services/rust-slim
      args:
        PUID: ${PUID:-1000}
        PGID: ${PGID:-1000}
        RUST_VERSION: ${RUST_VERSION:-latest}
    image: dev-container-rust:${RUST_VERSION:-latest}-slim  	
    container_name: ${CONTAINER_NAME:-dev_container}_rust       
    volumes:
      - ./projects:/projects:z
      - cargo_cache:/usr/local/cargo/registry:z
    ports:
      - "${RUST_PORT:-8080}:8080"
    networks:
      - net
      
networks:
  net:
    name: ${CONTAINER_NAME:-dev_container}_net
    driver: bridge

volumes:
  cargo_cache:
