services:
  # Rust Lang
  rust:
    build:
      context: ./services/rust
      args:
        PUID: ${PUID:-1000}
        PGID: ${PGID:-1000}
        RUST_VERSION: ${RUST_VERSION:-latest}
    image: dev-container-rust:${RUST_VERSION:-latest}	
    container_name: ${CONTAINER_NAME:-dev_container}_rust       
    volumes:
      - ./app:/app:z
      - cargo_cache:/usr/local/cargo:z
    ports:
      - "${RUST_PORT:-8080}:8080"
    networks:
      - net
      
networks:
  net:
    name: ${CONTAINER_NAME:-dev_container}_net
    driver: bridge

volumes:
  cargo_cache:
